### ISSUE TITLE
Marking a todo as completed

### ISSUE THREAD

**Issue by kamos1** [anderswood/2DoBox-Pivot#5]
- [x] add 'completed task' button to each card

- [x] gray out card upon clicking 'completed task' button

- [x] upon reloading the page completed tasks should not display

- [x] add a 'show completed todos' button

- [x] upon clicking 'show completed todos' button the completed todos will be load at the top of the list
